version: "3"

dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

tasks:
  generate:
    dir: "./proto"
    cmds:
      - buf generate
    desc: "生成proto产物"
    aliases: [gen]
  update:
    dir: "./proto"
    cmds:
      - buf dep update
    desc: "更新"
    aliases: [up]
